# -*- coding: utf-8 -*-
"""
Research shelf data.

Every entry is drawn from the corresponding folder README in
github.com/odin-loki/Ideas. Claims are reproduced with their stated
basis and evidence tier -- nothing here is upgraded beyond what the
source document actually claims.

TIERS
  speculative   theory or design only, no in-house measurement
  design        specification / design document, implementation partial
  reference     reference implementation exists and runs
  result        result-bearing: experiments run, numbers reported
  validated     independently or externally validated  (nothing is here yet)
"""

TIER_LABEL = {
    'speculative': ('Speculative',           'badge--red',    'Theory or design only. No in-house measurement.'),
    'design':      ('Design document',       'badge--amber',  'Specified in detail; implementation partial or absent.'),
    'reference':   ('Reference implementation','badge--blue', 'Code exists and runs. Performance not independently checked.'),
    'result':      ('Result-bearing',        'badge--teal',   'Experiments were run and the numbers are reported here.'),
}

# basis codes for the claims ledger
BASIS = {
    'measured':  ('Measured',    'ok',   'Author-run experiment on the stated setup.'),
    'derived':   ('Derived',     'vi',   'Follows from the stated construction or proof.'),
    'projected': ('Projected',   'warn', 'Paper-stated projection, not an author-run benchmark.'),
    'cited':     ('Cited',       '',     'Taken from external literature.'),
    'synthetic': ('Synthetic',   'warn', 'Measured, but on synthetic rather than real data.'),
}

RESEARCH = [
{
  'slug': 'aria-aead',
  'name': 'ARIA',
  'title': 'ARIA — an AEAD scheme that cannot lose nonce synchronisation',
  'field': 'Cryptography',
  'tier': 'reference',
  'folder': 'ARIA Encryption Algorithm',
  'blurb': 'Authenticated encryption that derives the nonce from the message and session key instead of transmitting it, making sender/receiver drift structurally impossible.',
  'lede': 'AES-GCM and ChaCha20-Poly1305 both fail badly when a nonce desynchronises after loss of state. ARIA removes the failure mode by never transmitting a nonce at all: it derives one deterministically from the message and the session key, over a three-layer algebraic tower of finite fields.',
  'what': [
    'ARIA is an authenticated-encryption scheme built to address one specific operational vulnerability in modern AEAD standards: nonce desynchronisation under loss of state. In deployed systems this is not a theoretical concern — a device that reboots, a link that drops, a replica that forks, and the nonce discipline that guarantees security is gone.',
    'Rather than transmit the nonce, ARIA computes it from the message and session key as <code>N(M, sk) = C(M, sk) · β_vec</code>, with a Vandermonde matrix derived from the session key. Recovery from drift is not a recovery procedure; there is nothing to resynchronise.',
    'The construction rests on a three-layer tower: a GF(2<sup>256</sup>) base using the irreducible polynomial <code>x²⁵⁶ + x¹⁰ + x⁵ + x² + 1</code>, a degree-8 extension L₂ for mid-layer mixing, and a degree-4 extension L₃ providing roughly 8192 bits of diffusion structure.',
  ],
  'claims': [
    ('Collision-resistance bound', 'Adv_COLL ≤ min(ε_PRF + 7Q²/2²⁵⁷, 2⁻⁸⁶)', 'derived', 'Two bounds converging on one advantage metric'),
    ('Classical security at Q ≤ 2⁶⁴', '~2⁻¹²⁶', 'derived', 'Realistic query limit substituted into the bound'),
    ('Classical ISD hardness', '~2⁸⁶', 'derived', 'Syndrome-decoding analysis on a [2048, 256] code'),
    ('Quantum advantage', '~2⁴³', 'derived', 'Motivates migration to GF(2⁵¹²)'),
    ('GF(2²⁵⁶) multiplication', '~46.1 µs', 'measured', 'Pure Python reference, author hardware'),
    ('Encryption throughput', '155–175 ops/sec', 'measured', 'Pure Python reference, author hardware'),
    ('Full AEAD round-trip', '68–69 ops/sec', 'measured', 'Pure Python reference, author hardware'),
  ],
  'methods': [
    ('Three-layer algebraic tower', 'GF(2²⁵⁶) base, degree-8 extension for mixing, degree-4 extension for diffusion.'),
    ('Deterministic nonce derivation', 'The nonce is a function of message and session key, so it is never a transmitted, losable value.'),
    ('Vandermonde key schedule', 'The β vector used in nonce computation is derived from the session key.'),
    ('Syndrome-decoding security analysis', 'Hardness argued against a [2048, 256] code under information-set decoding.'),
  ],
  'limits': [
    'No formal EUF-CMA proof for tag unforgeability.',
    'The Meta-DAG entropy source has no formal reduction to a hardness assumption.',
    'Post-quantum margin is insufficient without upgrading the field to GF(2⁵¹²).',
    'Zero external cryptographic audit.',
    'No side-channel analysis and no timing resistance.',
  ],
  'status': 'Prototype. Explicitly not for production use.',
  'callout': ('red', 'Do not deploy this.', 'A cryptographic scheme with no external audit, no side-channel analysis and no unforgeability proof is a research object, not a security control. It is published so it can be attacked, which is the only way it ever becomes more than a prototype.'),
},
{
  'slug': 'compression',
  'name': 'Izaac · GRIA · NMP',
  'title': 'Three frameworks for compression under one vocabulary',
  'field': 'Information theory',
  'tier': 'result',
  'folder': 'Compression Algorithms',
  'blurb': 'Shared-PRF coordination, graded reversibility, and neural networks treated as measurable compression operators — unified under one information-theoretic vocabulary.',
  'lede': 'Lossless coding, distribution compression and neural representation are usually studied with three separate vocabularies. This work proposes one: a deterministic shared pseudo-random stream σ, a reversibility grade α, and a spectral exponent that makes a neural network measurable as a compressor.',
  'what': [
    '<strong>Izaac</strong> introduces deterministic shared-PRF coordination together with a "free broadcast channel" meta-theorem. The unifying mechanism is σ, a deterministic shared pseudo-random stream of size Θ(λ + log k), which supports fast-forward in O(log n) time — O(1) in CTR mode.',
    '<strong>GRIA</strong> grades compression systems along a reversibility axis α ∈ [0, 1], so that lossless and lossy are endpoints of one scale rather than two categories. Eleven axioms define its algebra.',
    '<strong>NMP</strong> treats neural networks as compression operators with a measurable spectral exponent, reported at α ≈ 0.851 ± 0.122. Ten theorems structure the Izaac foundation; the frameworks ship reference Python implementations and technical memoranda.',
  ],
  'claims': [
    ('Spectral exponent (NMP)', 'α ≈ 0.851 ± 0.122', 'measured', 'Across NMP configurations'),
    ('MDL-optimal bottleneck', 'P* = 45 → 218.7:1 effective ratio', 'measured', 'Memoriser study: 30 documents, 512 hidden dims, 300 epochs'),
    ('GRIA J-score', '0.889 vs 0.742 baseline', 'measured', 'Jeffries-style metric'),
    ('Theoretical J ceiling', 'J ≤ 0.951', 'derived', 'From the GRIA axioms'),
    ('Coding improvement', 'gzip ~3.2 → ~1.2 bits/char style gains', 'measured', 'Author-reported, specific setup'),
    ('Fast-forward cost', 'O(log n), O(1) in CTR mode', 'derived', 'Property of the σ construction'),
    ('Regression fit across NMP configs', 'R² 0.75 – 0.97', 'measured', 'Range, not a single figure'),
  ],
  'methods': [
    ('Ten theorems (Izaac)', 'Structure the shared-PRF coordination foundation.'),
    ('Eleven axioms (GRIA)', 'Define the algebra of graded reversibility on α ∈ [0, 1].'),
    ('Spectral measurement (NMP)', 'Networks characterised by a measurable spectral exponent rather than a parameter count.'),
    ('Reference implementations', 'Python, with technical memoranda giving experimental specifications.'),
  ],
  'limits': [
    'Requires secure σ setup — compromise causes predictability collapse.',
    '"Shannon-breaking" claims depend on Wyner–Ziv side-information setups. They are not unconditional violations of the source coding theorem.',
    'The consensus tables underspecify: leader selection requires zero messages, but proposal propagation still demands messaging.',
    'Author-reported metrics only. No third-party benchmarks.',
    'R² varies widely (0.75 – 0.97) across NMP configurations.',
  ],
  'status': 'Result-bearing, with reference implementations. No external replication.',
  'callout': ('amber', 'On the "Shannon-breaking" language.', 'The README says this plainly and it is worth repeating: the improvement comes from a Wyner–Ziv side-information setup. Given shared side information, beating a no-side-information baseline is expected, not a violation of anything. The interesting claim is the size of σ, not a broken bound.'),
},
{
  'slug': 'uhpm',
  'name': 'UHPM',
  'title': 'UHPM — memory retrieval and inference under one loss function',
  'field': 'AI & machine learning',
  'tier': 'result',
  'folder': 'Long Reasoning and Thinking NN',
  'blurb': 'Locality-sensitive-hash memory and hierarchical predictive coding unified under a single free-energy functional, reporting a 289× query-latency speedup over full attention at 100K tokens.',
  'lede': 'If memory retrieval and inference are both Bayesian operations, they should share one loss function rather than being welded together at runtime. UHPM is what happens when you take that seriously: an LSH-based memory hierarchy and hierarchical predictive coding derived from a single variational free-energy functional.',
  'what': [
    'UHPM (Unified Hash-Predictive Memory) merges LSH-based memory with hierarchical predictive coding under one variational framework. The argument is structural: two systems that are both doing Bayesian work should not be optimising two different objectives and reconciling the results at inference time.',
    'The memory is a three-level hierarchy over 100 / 1,000 / 10,000-token segments with 64-bit LSH, compressed to a centroid dimension of d′ = 64. Inference runs roughly ten Bayesian refinement iterations with a stopping criterion of ‖Δs‖ &lt; 10⁻³.',
    'The efficiency numbers are large, and so are the caveats attached to them — the benchmarks are synthetic topic-cluster corpora with fixed, non-overlapping segments, and retrieval fidelity is 80–90% of exact attention rather than 100%.',
  ],
  'claims': [
    ('Query-latency speedup at 100K tokens', '289× (8.1 ms vs 2,340 ms)', 'synthetic', 'vs full attention, synthetic corpus'),
    ('Memory reduction', '744× (2.2 MB vs 1,638 MB)', 'synthetic', 'vs full attention, synthetic corpus'),
    ('Retrieval fidelity', '80–90% of exact attention', 'synthetic', 'Explicitly not 100%'),
    ('Memory hierarchy', '100 / 1,000 / 10,000-token segments, 64-bit LSH', 'derived', 'Architecture parameter'),
    ('Compressed centroid dimension', "d′ = 64", 'derived', 'Architecture parameter'),
    ('Refinement iterations', '~10, stopping at ‖Δs‖ < 10⁻³', 'derived', 'Inference procedure'),
    ('Crossover point', 'Slower than simple k-NN below ~7,500 tokens', 'synthetic', 'Honest negative result'),
  ],
  'methods': [
    ('Single free-energy functional', 'Memory and inference derived from one objective rather than composed at runtime.'),
    ('Three-level LSH hierarchy', '64-bit hashes over nested segment sizes.'),
    ('Iterative Bayesian refinement', 'Roughly ten iterations with an explicit convergence criterion.'),
    ('60-page derivation', 'The mathematical framework is written out, not asserted.'),
  ],
  'limits': [
    'Experiments use synthetic topic-cluster corpora with fixed, non-overlapping segments — not natural text.',
    'Hashes are random and static rather than learned. Learned hashing is flagged as future work.',
    'Retrieval fidelity is 80–90% of exact attention, not equivalence.',
    'Slower than simpler k-NN approaches below roughly 7,500 tokens.',
    'Preprint dated March 2026. Not peer-reviewed.',
  ],
  'status': 'Paper, 60-page derivation, Python implementations, and a runnable demonstration on synthetic data.',
  'callout': ('amber', 'Read the 289× carefully.', 'It is a real measurement on a synthetic corpus with fixed, non-overlapping segments and static random hashes — close to the best case this design can face. The honest headline is not "289× faster than attention"; it is "289× on a benchmark constructed to suit it, with 80–90% fidelity, and slower than k-NN under 7,500 tokens".'),
},
{
  'slug': 'neural-decompiler',
  'name': 'Neural Decompiler',
  'title': 'Neural Decompiler — decompilation as conditional sequence modelling',
  'field': 'AI & machine learning',
  'tier': 'reference',
  'folder': 'Neural Decompiler',
  'blurb': 'An encoder–decoder Transformer with hierarchical memory and a load-balanced mixture of experts, reframing assembly-to-source recovery as a sequence modelling problem.',
  'lede': 'Classical decompilation is a pipeline: disassembly, control-flow recovery, type reconstruction, pretty-printing. This work asks what happens if you treat the whole thing as one conditional sequence model — and is explicit that the answer is "a coherent trainable architecture", not a state-of-the-art recovery system.',
  'what': [
    'A PyTorch research implementation that reframes binary decompilation as conditional sequence modelling. Rather than a staged compiler pipeline run in reverse, an encoder–decoder Transformer maps assembly to source directly.',
    'Three learnable mechanisms carry the design: a hierarchical memory module of learnable slots accessed by multi-head attention with gated fusion across levels; pre-norm GELU Transformer encoder and decoder layers with learned position embeddings; and a mixture of experts split into binary-focused and language-focused families.',
    'The MoE routing is load-balanced by an auxiliary loss <code>λ‖p̄ − u‖²</code>, added to a token cross-entropy with label smoothing. The bundled synthetic corpus validates the pipeline mechanically — forward pass, shape checks, loss decrease — and nothing more.',
  ],
  'claims': [
    ('Architecture', 'Encoder–decoder Transformer, pre-norm GELU', 'derived', 'Implemented and runs'),
    ('Hierarchical memory', 'Learnable slots, multi-head access, gated fusion', 'derived', 'Implemented'),
    ('Mixture of experts', 'Binary-focused and language-focused families', 'derived', 'Implemented'),
    ('MoE load balancing', 'Auxiliary loss λ‖p̄ − u‖²', 'derived', 'Implemented'),
    ('Pipeline validation', 'Forward pass, shape checks, loss decrease', 'synthetic', 'On the bundled synthetic corpus only'),
    ('Recovery quality on real binaries', 'Not claimed', 'projected', 'Explicitly out of scope at this stage'),
  ],
  'methods': [
    ('Conditional sequence modelling', 'Assembly to source as one learned mapping, not a staged inversion.'),
    ('Gated hierarchical memory', 'Learnable slots read by attention, fused across levels by a gate.'),
    ('Load-balanced MoE', 'Routing regularised so experts are actually used.'),
    ('Synthetic corpus harness', 'Validates that the training loop is mechanically correct.'),
  ],
  'limits': [
    'This is a trainable architecture and reference training loop, not a state-of-the-art recovery system on full binaries.',
    'Real deployment needs lifted-assembly plus source datasets with recorded compiler flags — which the project does not have.',
    'Long sequences and large vocabularies are not properly handled yet.',
    'Neural output is not type-checked or tested; nothing validates that the emitted source compiles or behaves.',
    'Dense mixtures may need replacing with sparse MoE kernels to be practical.',
  ],
  'status': 'Reference implementation with training loop, inference harness and synthetic dataset validation.',
  'callout': ('violet', 'Compare with the shipping decompiler.', 'RetDec Imortek takes the opposite bet: a deterministic decompiler is the auditable baseline, and neural refinement is optional, gated by a compile check, and off by default. This folder is the research line; that product is what survived contact with the requirement to be trustworthy.'),
  'related': ('/retdec.html', 'RetDec Imortek — the shipping decompiler'),
},
{
  'slug': 'modelling-aes',
  'name': 'Modelling AES',
  'title': 'Modelling AES — two neural attacks, both honestly negative',
  'field': 'Cryptography',
  'tier': 'result',
  'folder': 'Modelling AES',
  'blurb': 'A paired study attacking AES-128 from both directions with neural networks, reporting that neither works — and quantifying exactly how far short each falls.',
  'lede': 'Two studies, run properly, that both failed. Key recovery reached 0.675% against a 0.3906% random baseline — a difference that is not statistically significant. Output replication produced byte entropy indistinguishable from AES and then failed chi-squared uniformity at p ≈ 0. Published because a well-documented dead end is worth more than a quiet one.',
  'what': [
    'The <strong>inverse direction</strong> asks whether a neural network can recover an AES-128 key. Best first-byte recovery accuracy was 0.675% against a 0.3906% random baseline: an improvement of 0.28 percentage points, z = 1.84, p = 0.066 — not statistically significant. Training loss fell to 0.27 nats while test accuracy stayed at chance, which is the signature of pure memorisation.',
    'The <strong>forward direction</strong> asks whether a network can replicate AES output. The best GAN-BCE configuration at 25 epochs reached 7.983 of 8.0 bits byte entropy with a gzip ratio of 1.0005 — matching AES on both. It then failed chi-squared uniformity at p ≈ 0 across every architecture tested, and the trained generator showed mean inter-byte correlation of 0.433 where AES shows approximately zero.',
    'Three theoretical barriers frame the inverse work: entropy indistinguishability, pseudorandom collapse, and combinatorial infeasibility. The last is the memorable one — 50% coverage of a single AES-128 key would require roughly 5.90 × 10⁸ TB of storage.',
  ],
  'claims': [
    ('First-byte key recovery', '0.675% vs 0.3906% baseline', 'measured', 'z = 1.84, p = 0.066 — not significant'),
    ('Training vs test behaviour', 'Loss 0.27 nats, test at chance', 'measured', 'Signature of pure memorisation'),
    ('State-space barrier', '~5.90 × 10⁸ TB for 50% coverage of one key', 'derived', 'Combinatorial infeasibility argument'),
    ('Best byte entropy (forward)', '7.983 / 8.0 bits', 'measured', 'GAN-BCE at 25 epochs'),
    ('Gzip ratio', '1.0005', 'measured', 'Matches AES'),
    ('Chi-squared uniformity', 'Fails at p ≈ 0', 'measured', 'Across all architectures tested'),
    ('Inter-byte correlation', '0.433 (AES ≈ 0)', 'measured', 'Final WGAN + sequential critic'),
    ('Statistical tests passed', '2 of 4', 'measured', 'Final configuration'),
  ],
  'methods': [
    ('Five experiments, variable-key protocols', 'Inverse direction, AES-128.'),
    ('Six architectures compared', 'Shallow MLP, deep MLP, LSTM, GAN-BCE, WGAN-GP, WGAN with sequential critic and chi-squared auxiliary loss.'),
    ('Three theoretical barriers', 'Entropy indistinguishability, pseudorandom collapse, combinatorial infeasibility.'),
    ('Honest scaffolding', 'The <code>Break AES with NNs/</code> directory is explicitly non-runnable and kept as documentation of the dead end.'),
  ],
  'limits': [
    'Nothing in this work undermines the security of AES under standard threat models.',
    'Side-channel attacks and reduced-round toy ciphers remain feasible and are explicitly out of scope.',
    'The result is not a cryptanalytic breakthrough and is not presented as one.',
    'The accompanying scaffolding is non-runnable as written — undefined data loaders, tensor mismatches.',
  ],
  'status': 'Both papers are result-bearing and peer-research quality. The conclusion is negative.',
  'callout': ('teal', 'This is what the standard is for.', 'A result of p = 0.066 is the kind of number that gets rounded to "promising signal" in a lot of write-ups. Here it is reported as not significant, next to the memorisation diagnostic that explains it. The negative result is the contribution.'),
},
{
  'slug': 'gf2-algebra',
  'name': 'GF(2) Algebra',
  'title': 'GF(2) algebra — seven papers on the smallest interesting field',
  'field': 'Mathematics',
  'tier': 'result',
  'folder': 'GF2 Algebra and Applications',
  'blurb': 'From an exhaustive enumeration of all 16 binary operations to permutation polynomials, circuit optimisation and differentiable logic gates — including a uniqueness theorem for AND.',
  'lede': 'GF(2) has 16 binary operations. Enumerate them all and something falls out: AND is the only nontrivial operation that forms a ring with XOR. The series runs from that result through permutation polynomials, bifurcation dynamics, circuit minimisation and what a neural network chooses when you let it learn logic gates.',
  'what': [
    'A seven-paper series on the binary finite field GF(2). Paper 1 establishes the GF(2) Ring Uniqueness Theorem by exhaustive enumeration: AND is the <em>only</em> nontrivial operation that forms a ring with XOR.',
    'The cryptographic thread identifies the AES inverse <code>x⁻¹ = x²⁵⁴</code> as one of 128 permutation polynomials on GF(2⁸), verified through the Monomial Permutation Criterion: <code>xᵏ</code> permutes GF(2ⁿ) if and only if <code>gcd(k, 2ⁿ − 1) = 1</code>.',
    'The applied thread reports gate-count reductions — Rule 110 from 19 gates to 6, a 68% cut; full-adder sum down 78%; XOR down 80% — and a differentiable logic gate network that favoured AND in 10 of 96 slots and NOR in 11 of 96, against a uniform expectation of 6.',
  ],
  'claims': [
    ('GF(2) Ring Uniqueness Theorem', 'AND is the only nontrivial ring partner for XOR', 'derived', 'Exhaustive enumeration, computer verified'),
    ('AES inverse classification', 'x²⁵⁴ is 1 of 128 permutation polynomials on GF(2⁸)', 'derived', 'Monomial Permutation Criterion'),
    ('Monomial Permutation Criterion', 'xᵏ permutes GF(2ⁿ) iff gcd(k, 2ⁿ−1) = 1', 'derived', 'Stated and verified'),
    ('Rule 110 gate reduction', '19 → 6 gates (68%)', 'measured', 'Circuit optimisation'),
    ('Full-adder sum reduction', '78%', 'measured', 'Circuit optimisation'),
    ('XOR reduction', '80%', 'measured', 'Circuit optimisation'),
    ('Learned gate preference', 'AND 10/96, NOR 11/96 vs uniform 6/96', 'measured', '2,000 steps, 6 random seeds'),
  ],
  'methods': [
    ('Exhaustive enumeration', 'All 16 binary operations, with computer verification.'),
    ('Algebraic normal form', 'ANF / Zhegalkin conversion throughout.'),
    ('Numerical Jacobian analysis', 'For contraction bounds and bifurcation mapping.'),
    ('Differentiable logic gate network', '2,000 training steps across 6 random seeds.'),
  ],
  'limits': [
    'The empirical work is small-network and synthetic, not industrial scale.',
    'No third-party formal-methods verification of the enumeration results.',
    "Paper 7's ECE relationship is a framework or heuristic, not a proven law.",
  ],
  'status': 'Seven papers, computer-verified enumeration, reference experiments.',
  'callout': None,
},
{
  'slug': 'asset-tracking',
  'name': 'ARIA-INTEL',
  'title': 'ARIA-INTEL — multi-source tracking to actionable intelligence, on one CPU core',
  'field': 'Tracking & sensors',
  'tier': 'reference',
  'folder': 'Asset Tracking Algorithm',
  'blurb': 'A PMBM random-finite-set tracker with pattern-of-life modelling, eight tradecraft detectors and Bayesian threat scoring — 2,363 lines, NumPy and SciPy only, 28 ms per scan.',
  'lede': 'One Python module, two dependencies, no GPU. ARIA-INTEL runs a Poisson Multi-Bernoulli Mixture tracker with Mixed Ornstein–Uhlenbeck motion, then routes confirmed tracks through pattern-of-life anomaly detection, eight tradecraft detectors and Dempster-Shafer threat fusion — at a median 28 ms per scan on a single core.',
  'what': [
    'ARIA-INTEL converts raw multi-source location observations into ranked intelligence. It is a single Python module of roughly 2,363 lines requiring only NumPy and SciPy, and it processes a scan in a median 28 milliseconds on one CPU core with no GPU.',
    'The tracking core is a Poisson Multi-Bernoulli Mixture random-finite-set tracker with Mixed Ornstein–Uhlenbeck motion modelling and 320-particle filtering, using Gibbs-sampled data association over 14 sweeps rather than nearest-neighbour assignment. Every track carries an explicit Bernoulli existence probability.',
    'Downstream of tracking sit spatio-temporal pattern-of-life Gaussian mixtures, eight hot-swappable detectors (rendezvous warning with three stacked geometric methods, parallel-route surveillance, mode transition, loiter, dead drop, chokepoint, network analysis) and 8-dimensional Beta-Monte-Carlo threat integration via Dempster-Shafer fusion. Domain changes — urban HUMINT, maritime, airspace, convoy, city-camera, border, fugitive — are configuration swaps through <code>DomainProfile</code> objects, not code changes.',
  ],
  'claims': [
    ('Median scan latency', '28 ms, single CPU core', 'measured', 'No GPU'),
    ('Throughput', '~20 scans/second', 'measured', 'Same setup'),
    ('Rendezvous warning recall', '100% (20/20 scenarios)', 'synthetic', 'Synthetic scenarios, 28.1-minute mean lead time'),
    ('Mean position error', '21.8 m', 'synthetic', 'Synthetic scenario generators'),
    ('Scaling', 'Linear to 50+ tracks', 'measured', ''),
    ('Data association', 'Gibbs sampling, 14 sweeps', 'derived', 'vs nearest-neighbour'),
    ('Motion filtering', '320 particles', 'derived', 'Mixed Ornstein–Uhlenbeck'),
    ('Module size', '~2,363 lines, NumPy + SciPy only', 'measured', ''),
  ],
  'methods': [
    ('PMBM random-finite-set tracking', 'Per-track Bernoulli existence probability rather than a hard track list.'),
    ('Mixed Ornstein–Uhlenbeck motion', 'With 320-particle filtering.'),
    ('Gibbs-sampled association', '14 sweeps, a principled alternative to nearest-neighbour.'),
    ('Eight hot-swappable detectors', 'Rendezvous, parallel-route, mode transition, loiter, dead drop, chokepoint, network role.'),
    ('Dempster-Shafer threat fusion', '8-dimensional Beta-Monte-Carlo integration.'),
    ('DomainProfile polymorphism', 'Scan period, rendezvous horizon, spatial gating and motion libraries as configuration.'),
  ],
  'limits': [
    'No third-party validation of any figure.',
    'Pattern-of-life modelling requires at least 15 observations before it produces anything.',
    'The Paper 2 deployment profiles are specifications, not shipped code.',
    'No camera re-identification pipeline is included.',
    'No audit-trail logging is implemented — which matters for the law-enforcement use cases the brief describes.',
  ],
  'status': 'Reference implementation, three research documents, synthetic scenario generators. Licensed AGPL-3.0.',
  'callout': ('amber', 'Where this would need to be much stronger.', 'The briefing document targets law-enforcement and intelligence audiences. Software used to rank people as threats needs audit-trail logging, third-party validation and a fairness review before it goes anywhere near an operational decision — and by the author’s own list, it currently has none of the three. SENTINEL, the shipping product, was built with provenance chains for exactly this reason.'),
  'related': ('/sentinel.html', 'SENTINEL — the shipping analyst tool'),
},
{
  'slug': 'filtering',
  'name': 'GH-SR-IMM',
  'title': 'GH-SR-IMM — separating heavy tails from manoeuvre',
  'field': 'Tracking & sensors',
  'tier': 'result',
  'folder': 'Filtering',
  'blurb': 'A heavy-tailed multi-target tracker that decouples outlier robustness from manoeuvre handling, reporting a 51.6% average GOSPA improvement.',
  'lede': 'Standard trackers conflate two different problems: measurement noise with heavy tails, and targets that manoeuvre. Handle them with one mechanism and each degrades the other. GH-SR-IMM separates them — and fixes a specific failure where a naive heavy-tailed likelihood silently decides every measurement is clutter.',
  'what': [
    'The tracker combines Normal-Inverse-Gaussian measurement noise with conjugate scale updates, a three-model Interacting-Multiple-Model bank (constant velocity, constant acceleration with AR jerk, and an H∞ adversarial model), and square-root cubature Kalman filtering for numerical stability under heavy-tailed posteriors.',
    'The central correction is in the data association step. Feeding a raw generalised-hyperbolic likelihood into joint probabilistic data association silently overweights the hypothesis that all measurements are clutter. The fix is to use the GH posterior covariance <code>R_eff</code> inside a <em>Gaussian</em> association likelihood — keeping heavy-tail robustness in estimation without letting it corrupt association.',
    'The result of separating the two concerns: GH estimation applies per-model, IMM mixing handles manoeuvre adaptation, and neither is asked to compensate for the other.',
  ],
  'claims': [
    ('Multi-target GOSPA improvement', '51.6% average', 'measured', 'Across four scenarios'),
    ('Peak GOSPA improvement', '72.8%', 'measured', 'Best of the four scenarios'),
    ('Single-target composite score', '1.090', 'measured', '38% better than Student-t baseline'),
    ('vs variational-Bayes baseline', '69% better', 'measured', 'Single-target composite'),
    ('Association correction', 'R_eff inside a Gaussian likelihood', 'derived', 'The core methodological fix'),
    ('Filter bank', '3 models: CV, CA+AR jerk, H∞', 'derived', 'IMM'),
  ],
  'methods': [
    ('Normal-Inverse-Gaussian noise', 'With conjugate scale updates.'),
    ('Three-model IMM', 'Constant velocity, constant acceleration with AR jerk, H∞ adversarial.'),
    ('Square-root cubature KF', 'Stable covariance factorisation under heavy-tail posteriors.'),
    ('IW-Q / IW-R adapters', 'Online process and measurement noise tracking.'),
    ('AR-ρ estimation', 'Online jerk autocorrelation for the acceleration model.'),
    ('ACF monitor', 'Fault detection through innovation analysis.'),
  ],
  'limits': [
    'The IMM transition matrix is fixed, not learned online.',
    'The multi-target benchmark assumes a known track count and near-truth initialisation — a generous setup.',
    'One hyperparameter variant does not consistently beat the baseline.',
    'Single-target and multi-target implementations differ in architectural completeness.',
  ],
  'status': 'Result-bearing across four benchmark scenarios.',
  'callout': None,
  'demo': 'filtering',
},
{
  'slug': 'physics',
  'name': 'NLFGN-UFT',
  'title': 'Non-local field-gravity, and an argument about superluminal recession',
  'field': 'Physics',
  'tier': 'speculative',
  'folder': 'Physics',
  'blurb': 'A variational non-local gravity programme that keeps causal messaging at speeds ≤ c, paired with an essay arguing that superluminal recession is an interpretational split rather than a failure of ΛCDM.',
  'lede': 'Two papers with very different confidence levels. One is a speculative unification programme grounded in a stated variational action, with its couplings admittedly unpinned. The other is a careful essay arguing that the "galaxies receding faster than light" dispute is a disagreement between rigorous GR positions, not evidence that anything is broken.',
  'what': [
    '<strong>NLFGN-UFT</strong> proposes a non-local gravity theory that retains causal messaging at speeds ≤ c — explicitly distinguished from folklore "instantaneous non-locality". The field decomposes as <code>φ = φ_f + φ_e + φ_int + Σ φ_subtle + ΣΣ φ_network</code>, with advanced and retarded kernels whose exponential decay is parameterised by <code>λ = ℏ/(m·v_field)</code>. Newton, Friedmann and growth equations are modified to carry network contributions, and the quantum state is composite: <code>|Ψ⟩ = |ψ_base⟩ ⊗ |ψ_network⟩ ⊗ |ψ_subtle⟩</code>.',
    'The <strong>superluminal recession essay</strong> takes a different tack. Recession velocities above c — the CMB at roughly 3.2c today, about 58.1c at emission — are argued to reflect a genuine interpretational split between rigorous GR positions rather than a failure of ΛCDM. Sean Carroll’s dimensional critique and the coordinate-representation schools yield competing but mathematically valid readings.',
    'The essay’s conclusion is deliberately modest: this is a pedagogical crisis in cosmology, not an empirical breakdown, and the interpretational disagreement does not change FLRW-derived observables.',
  ],
  'claims': [
    ('Causal non-locality', 'Messaging retained at speeds ≤ c', 'derived', 'Distinguishes the programme from instantaneous non-locality'),
    ('Field decomposition', 'φ = φ_f + φ_e + φ_int + Σφ_subtle + ΣΣφ_network', 'derived', 'From the stated action'),
    ('Kernel decay parameter', 'λ = ℏ/(m·v_field)', 'derived', 'Exponentially decaying advanced + retarded kernels'),
    ('CMB recession today', '~3.2c', 'cited', 'Standard FLRW calculation'),
    ('CMB recession at emission', '~58.1c', 'cited', 'Standard FLRW calculation'),
    ('Constraint sources', 'LIGO/Virgo bounds', 'cited', 'Repository-native results are mostly literature cites'),
    ('Original calculations', 'Incomplete', 'projected', 'Stated by the author'),
  ],
  'methods': [
    ('Variational construction', 'The action is stated explicitly rather than assumed.'),
    ('Advanced and retarded kernels', 'With exponential decay structure.'),
    ('Modified field equations', 'Newton, Friedmann and growth equations carrying network contributions.'),
    ('Conceptual analysis (essay)', 'Defends standard FLRW machinery while exposing the interpretational tension.'),
  ],
  'limits': [
    'Couplings α₁, α₂ and γ are unpinned.',
    'Quantitative cosmology simulations are beyond present analytic scope.',
    'Network sector phase structure is unresolved.',
    'Environment-dependent GUP could conflict with atomic-scale precision measurements unless heavily suppressed.',
    'Neither document reports in-house measurements. Repository-native results are mostly literature citations.',
  ],
  'status': 'Highly speculative. The programme is action-grounded but incomplete; the essay is philosophical rather than phenomenological.',
  'callout': ('red', 'Filed under speculative, deliberately.', 'This is the most speculative item on the shelf and it is labelled that way in its own README. It is here because a stated action with admittedly unpinned couplings is a more useful research object than a vague intuition — not because anything in it is established.'),
},
{
  'slug': 'carbide',
  'name': 'HX-70 GradePlex',
  'title': 'Carbide tooling for HRC 40–70, where WC-Co gives out and CBN is too narrow',
  'field': 'Materials & engineering',
  'tier': 'design',
  'folder': 'Rockwell 50 to 70 Carbide',
  'blurb': 'A functionally-graded carbide substrate, a five-layer coating stack, and a forge-to-machine supply chain — targeting the gap between where conventional inserts fail and where CBN geometries exist.',
  'lede': 'Conventional WC-Co inserts fail around HRC 55. CBN inserts work above that but exist only in limited geometries. This is a three-part tooling system aimed squarely at the gap — written by a working toolmaker, with the performance figures labelled as projections rather than benchmarks.',
  'what': [
    'The <strong>HX-70 GradePlex substrate</strong> puts three functionally-graded zones in a single sintered billet: a hard, fine-grained working surface at 92.5% WC, 5.5% Co and 2.0% TaC/NbC inhibitors, reaching 2050–2100 HV30, over a tougher 13% Co core. It is achieved by controlled powder layering and HIP densification rather than by joining separate pieces.',
    'The <strong>TriboshieldPlus coating</strong> is a five-layer stack: a CrN bond layer, an AlCrN thermal barrier, an nc-AlTiSiN/a-Si₃N₄ hardness core at 42–46 GPa, a 40-bilayer AlCrN/AlTiSiN superlattice, and a DLC-Si friction layer below µ = 0.15.',
    'The <strong>forge-to-machine supply chain</strong> is the commercial half. Near-net-shape forging reduces the volume that has to be machined; the H13-breech exemplar shows a 40–45% cost reduction (AUD 190–240 against 340–420) and a 65–70% lead-time reduction (6–9 against 18–26 working days).',
  ],
  'claims': [
    ('Working-surface hardness', '2050–2100 HV30', 'cited', '92.5% WC / 5.5% Co / 2.0% TaC-NbC'),
    ('Core toughness', '13% Co', 'derived', 'Graded in one sintered billet'),
    ('Coating hardness core', '42–46 GPa', 'cited', 'nc-AlTiSiN/a-Si₃N₄'),
    ('Friction coefficient', 'µ < 0.15', 'cited', 'DLC-Si outer layer'),
    ('Tool life, HRC 55–60', '40–100% gain vs premium AlTiN', 'projected', 'Paper-stated projection'),
    ('Cost advantage over CBN, HRC 65–70', '60–70%', 'projected', 'Paper-stated projection'),
    ('Exemplar cost reduction', '40–45% (AUD 190–240 vs 340–420)', 'projected', 'H13 breech, forge-to-machine'),
    ('Exemplar lead-time reduction', '65–70% (6–9 vs 18–26 days)', 'projected', 'H13 breech'),
  ],
  'methods': [
    ('Controlled powder layering', 'Three graded zones formed in one billet before sintering.'),
    ('HIP densification', 'Hot isostatic pressing to close residual porosity.'),
    ('Five-layer PVD stack', 'Bond, thermal barrier, hardness core, superlattice, friction layer.'),
    ('Near-net-shape forging', 'Reduces the volume of material that must be removed by machining.'),
  ],
  'limits': [
    'Author-run machining benchmarks are unconfirmed — treat every performance gain as a paper-stated projection.',
    'Sintering tolerances are strict: carbon ±0.02 wt%, dew point ≤ −60°C, demanding specialised furnace control.',
    'Documentation is heavily cited from peer-reviewed metallurgy, but the system as a whole has not been built and tested end to end.',
  ],
  'status': 'Design document with heavy literature grounding. Not manufactured or benchmarked.',
  'callout': ('teal', 'The one with a day job behind it.', 'Odin Loch works as a toolmaker. Of everything on this shelf, this is the item where the author has direct trade experience of the problem being solved — which is worth exactly as much as the missing benchmarks say it is, and no more.'),
},
{
  'slug': 'economics',
  'name': 'EREM · SPX',
  'title': 'Wealth measured in megajoules, and a structural read on SPX call volume',
  'field': 'Policy & economics',
  'tier': 'design',
  'folder': 'Economics',
  'blurb': 'Two lines: recasting national wealth into physical energy units to break the circular dependency on monetary institutions, and five models converging on a 2028–2029 window for a gamma unwind.',
  'lede': 'EREM asks what happens if you measure national wealth in megajoules instead of currency — petroleum reserves, manufacturing capacity, food and water security, and human labour all recast into one physical unit. SPX asks why daily call notional grew 867-fold since 1999, and what five different curve families say about where that ends.',
  'what': [
    '<strong>EREM</strong> (Energy-Resource Economic Model) proposes measuring national wealth in megajoules rather than currency-denominated GDP. Total National Wealth is a weighted sum: <code>TNW = 0.40·NEW + 0.25·MWI + 0.20·FEW + 0.10·HLC + 0.05·IEF</code> — natural energy wealth, manufacturing, food/energy/water, human and labour capacity, and information efficiency. Currency issuance follows <code>Total_currency = 0.85 · TNW</code>, and exchange rates become a direct ratio of per-capita TNW between nations, with no monetary-policy translation layer.',
    '<strong>SPX Call Volume</strong> analyses structural instability in options markets. Daily SPX call notional reached USD 2.6 trillion on 7 May 2026 — an 867-fold increase since 1999. Five quantitative models (super-exponential, logistic, hyperbolic blow-up, Sornette log-periodic, and hazard-rate) all converge on a 2028–2029 base-case window for a high-speed gamma unwind, with roughly 10% early-tail probability inside 6–12 months, and a potential 20–35% index correction.',
    'The two lines share a method: take a quantity everyone treats as given, ask what it is actually measuring, and see whether a different unit or a different curve family changes the answer.',
  ],
  'claims': [
    ('TNW formula', '0.40·NEW + 0.25·MWI + 0.20·FEW + 0.10·HLC + 0.05·IEF', 'derived', 'Weights are priors, not derived'),
    ('Currency issuance rule', 'Total_currency = 0.85 · TNW', 'derived', 'Removes trust in monetary institutions from the loop'),
    ('Exchange rate', 'Direct per-capita TNW ratio', 'derived', 'No monetary-policy translation layer'),
    ('SPX daily call notional', 'USD 2.6 trillion, 7 May 2026', 'cited', 'Public CBOE statistics'),
    ('Growth since 1999', '867-fold', 'cited', 'Public CBOE statistics'),
    ('Base-case unwind window', '2028–2029', 'measured', 'Five models converge'),
    ('Early-tail probability', '~10% within 6–12 months', 'measured', 'Hazard-rate model'),
    ('Potential correction', '20–35% index', 'projected', 'Conditional on the unwind occurring'),
  ],
  'methods': [
    ('Physical-unit recasting', 'Every wealth component expressed in megajoules.'),
    ('Five model families (SPX)', 'Super-exponential, logistic, hyperbolic blow-up, Sornette log-periodic, hazard-rate.'),
    ('Public data anchoring', 'SPX analysis uses published CBOE statistics.'),
  ],
  'limits': [
    'EREM is v1.0 and theoretical. Its weighting coefficients are priors, not derived quantities.',
    'EREM requires national-level physical-resource audits that do not currently exist.',
    'The SPX analysis is explicitly not investment advice.',
    'Curve fitting extrapolates from a feedback-loop mechanism that could change structure or face regulatory intervention at any point.',
  ],
  'status': 'EREM v1.0, theoretical. SPX data-anchored to public statistics.',
  'callout': ('red', 'Not investment advice.', 'Five curve families agreeing on a window is five ways of extrapolating the same feedback loop, not five independent confirmations. The paper says so. Do not trade on it.'),
},
{
  'slug': 'fungal',
  'name': 'Fungal Network Algorithm',
  'title': 'Topology as memory — a network that stores history in its own shape',
  'field': 'AI & machine learning',
  'tier': 'design',
  'folder': 'Fungal Network Algorithm',
  'blurb': 'A bio-inspired self-organising network where edges and weights are the consequence of input history rather than the storage medium, growing and pruning by purely local rules.',
  'lede': 'In a conventional neural network the weights are where the information lives. This asks what a network looks like if the topology itself is the memory — where edges exist because history put them there, allocation is entirely local, and the structure grows, optimises and stabilises with no central control.',
  'what': [
    'The algorithm formalises four principles taken from fungal foraging. <strong>Topology as memory</strong>: weights and edges are not the storage medium, they are the consequence of input history. <strong>Decentralised emergence</strong>: all routing and allocation decisions stay local, with no central controller.',
    '<strong>Geometric state evolution</strong>: the network moves through exploration, connection, optimisation and stabilisation phases driven by simple local rules rather than a scheduler. <strong>Resource-driven adaptation</strong>: more "hyphae" are allocated to productive regions and unproductive connections are pruned, on local feedback alone.',
    'The folder ships a design-conversation transcript alongside three concept papers — a philosophy and applications overview, a single-instance mathematical model, and a distributed extension — plus a Python reference implementation.',
  ],
  'claims': [
    ('Topology as memory', 'Edges are the consequence of history, not the store', 'derived', 'Core design principle'),
    ('Decentralised emergence', 'All routing and allocation decisions are local', 'derived', 'No central control'),
    ('Four-phase evolution', 'Exploration → connection → optimisation → stabilisation', 'derived', 'Driven by local rules'),
    ('Resource-driven adaptation', 'Growth toward productive regions, pruning elsewhere', 'derived', 'Local feedback only'),
    ('Benchmark performance', 'Not measured', 'projected', 'No comparison against standard graph algorithms'),
  ],
  'methods': [
    ('Single-instance mathematical model', 'The core dynamics written out formally.'),
    ('Parallel/distributed extension', 'A second model for the distributed case.'),
    ('Python reference implementation', '<code>FungalNA.py</code>, v1.'),
  ],
  'limits': [
    'One generation shipped. v1 only; later versions are planned but not included.',
    'The work formalises four principles abstracted from fungal biology — it does not simulate actual fungi.',
    'Performance is entirely unvalidated. Theoretical and qualitative analysis only, with no benchmarks against standard graph algorithms.',
  ],
  'status': 'v1 design documents plus a Python reference implementation.',
  'callout': None,
},
]

# Every folder in the Ideas repository, for the index. Entries with a page get one.
ALL_FOLDERS = [
    ('100W Wideband Noise Generator', 'Electronics'),
    ('3 to 8 Value Boolean Algebra', 'Mathematics'),
    ('ARIA Encryption Algorithm', 'Cryptography'),
    ('Ashby Optimiser', 'Materials & engineering'),
    ('Asset Tracking Algorithm', 'Tracking & sensors'),
    ('Battle Sim', 'Defence & security'),
    ('Beauty Products', 'Chemistry & products'),
    ('CPU', 'Computer architecture'),
    ('Cocktails', 'Chemistry & products'),
    ('Compression Algorithms', 'Information theory'),
    ('Diamond Batterys', 'Materials & engineering'),
    ('Diffusion Welding', 'Materials & engineering'),
    ('Drugs', 'Chemistry & products'),
    ('Economics', 'Policy & economics'),
    ('Electromechnical Inspired Algorithms', 'AI & machine learning'),
    ('Filtering', 'Tracking & sensors'),
    ('Fungal Network Algorithm', 'AI & machine learning'),
    ('Future C++', 'Software & languages'),
    ('GF2 Algebra and Applications', 'Mathematics'),
    ('GM Enhancements', 'Biology & medicine'),
    ('General Math Papers', 'Mathematics'),
    ('Izaac as Side Data', 'Information theory'),
    ('Long Reasoning and Thinking NN', 'AI & machine learning'),
    ('Math Question Generator', 'Mathematics'),
    ('Modelling AES', 'Cryptography'),
    ('NN Shortcuts', 'AI & machine learning'),
    ('Neural Decompiler', 'AI & machine learning'),
    ('Neural Dust', 'Biology & medicine'),
    ('New Classes of Electrical Components', 'Electronics'),
    ('Physics', 'Physics'),
    ('Plastic Products', 'Chemistry & products'),
    ('Prime Number Generator', 'Mathematics'),
    ('Quantum Diamond Wafer', 'Materials & engineering'),
    ('Quantum Graph Optimisation', 'Mathematics'),
    ('RNGS', 'Cryptography'),
    ('Rockwell 50 to 70 Carbide', 'Materials & engineering'),
    ('Statistical Generation', 'AI & machine learning'),
    ('Statistical Scheduler', 'Software & languages'),
    ('Threat Asessments', 'Defence & security'),
    ('UCN AIs', 'Policy & economics'),
    ('UCN Political System', 'Policy & economics'),
    ('UN Political System', 'Policy & economics'),
    ('VDJ Inspired Algorithm', 'AI & machine learning'),
    ('Veritas', 'Defence & security'),
    ('Weapons-Defence', 'Defence & security'),
    ('Weapons-Police', 'Defence & security'),
]
